"""Test the release target summary generated by the release workflow."""

import json
import os
import re
import subprocess
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
WORKFLOW_PATH = REPO_ROOT / ".github" / "workflows" / "release.yml"
PACKAGE_PATH = Path("libs/example")
VERSION = "1.2.3"


def _workflow() -> dict:
    with WORKFLOW_PATH.open() as file:
        return yaml.safe_load(file)


def _resolve_sha_step() -> str:
    steps = _workflow()["jobs"]["setup"]["steps"]
    return next(step["run"] for step in steps if step.get("id") == "resolve-sha")


def _git(repository: Path, *args: str) -> str:
    """Run git in *repository*, raising with git's own diagnosis when it fails.

    `check=True` would raise a `CalledProcessError` whose message carries only
    argv and the exit status, which turns an infrastructure failure into an
    undebuggable report.
    """
    result = subprocess.run(
        ["git", "-C", str(repository), *args],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise AssertionError(
            f"git {' '.join(args)} failed (exit {result.returncode}):\n"
            f"{result.stdout}\n{result.stderr}"
        )
    return result.stdout.strip()


def _initialize_repository(repository: Path) -> str:
    _git(repository, "init", "--initial-branch=main")
    _git(repository, "config", "user.email", "release-test@example.com")
    _git(repository, "config", "user.name", "Release Test")
    _git(repository, "config", "commit.gpgSign", "false")
    # Background maintenance forked by `git commit` can hold the repository
    # locks while the next command runs, failing it with a lock error.
    _git(repository, "config", "gc.auto", "0")
    _git(repository, "config", "maintenance.auto", "false")

    package = repository / PACKAGE_PATH
    package.mkdir(parents=True)
    (package / "pyproject.toml").write_text(
        f'[project]\nname = "example"\nversion = "{VERSION}"\n'
    )
    _git(repository, "add", str(PACKAGE_PATH / "pyproject.toml"))
    _git(repository, "commit", "-m", f"release(example): {VERSION}")
    return _git(repository, "rev-parse", "HEAD")


def _write_fake_gh(directory: Path, requests: Path) -> Path:
    bin_dir = directory / "bin"
    bin_dir.mkdir()
    executable = bin_dir / "gh"
    # Record the args of every invocation so tests can assert the API is called
    # with the right endpoint and resolved SHA, then emit the canned response.
    executable.write_text(
        "#!/bin/sh\n"
        f'printf \'%s\\n\' "$*" >> "{requests}"\n'
        'printf \'%s\\n\' "$GH_API_RESPONSE"\n'
        'exit "$GH_API_EXIT"\n'
    )
    executable.chmod(0o755)
    return bin_dir


def _run_resolve_sha_step(
    repository: Path,
    *,
    api_response: str,
    api_exit: int = 0,
) -> tuple[str, subprocess.CompletedProcess[str], str]:
    release_sha = _initialize_repository(repository)
    output = repository / "github-output.txt"
    summary = repository / "github-summary.md"
    requests = repository / "gh-requests.txt"
    requests.touch()
    bin_dir = _write_fake_gh(repository, requests)
    env = {
        **os.environ,
        "GH_API_EXIT": str(api_exit),
        "GH_API_RESPONSE": api_response,
        "GH_TOKEN": "test-token",
        "GITHUB_OUTPUT": str(output),
        "GITHUB_REPOSITORY": "langchain-ai/deepagents",
        "GITHUB_SERVER_URL": "https://github.com",
        "GITHUB_SHA_FALLBACK": release_sha,
        "GITHUB_STEP_SUMMARY": str(summary),
        "INPUT_SHA": release_sha,
        "INPUT_VERSION": VERSION,
        "IS_DANGEROUS": "false",
        "PACKAGE": "example",
        "PATH": f"{bin_dir}{os.pathsep}{os.environ['PATH']}",
        "WORKING_DIR": str(PACKAGE_PATH),
    }
    result = subprocess.run(
        ["bash", "-eo", "pipefail", "-c", _resolve_sha_step()],
        cwd=repository,
        env=env,
        check=True,
        capture_output=True,
        text=True,
    )
    return summary.read_text(), result, requests.read_text()


def test_setup_job_can_read_pull_requests() -> None:
    permissions = _workflow()["jobs"]["setup"]["permissions"]
    assert permissions["contents"] == "read"
    assert permissions["pull-requests"] == "read"


def test_summary_links_merged_pr_associated_with_release_sha(tmp_path: Path) -> None:
    pulls = [
        {"number": 9999, "merged_at": None},
        {"number": 4857, "merged_at": "2026-07-20T18:53:15Z"},
    ]

    summary, _, requests = _run_resolve_sha_step(
        tmp_path,
        api_response=json.dumps(pulls),
    )

    assert (
        "| Associated PR | "
        "[#4857](https://github.com/langchain-ai/deepagents/pull/4857) |" in summary
    )
    assert "#9999" not in summary

    # The lookup must query the resolved release SHA's commit-pulls endpoint,
    # not the pre-resolution input or some other commit.
    resolved_sha = re.search(r"/commit/([0-9a-f]{40})", summary).group(1)
    assert (
        f"/repos/langchain-ai/deepagents/commits/{resolved_sha}/pulls" in requests
    )


def test_summary_omits_pr_row_when_no_merged_pr(tmp_path: Path) -> None:
    # A commit with no associated PR (direct push, or the github.sha fallback)
    # returns an empty array; unmerged PRs are filtered out. Either way the
    # jq filter must yield empty (never the string "null") so no row is written.
    responses = ("[]", json.dumps([{"number": 9999, "merged_at": None}]))
    for index, api_response in enumerate(responses):
        repository = tmp_path / f"case{index}"
        repository.mkdir()
        summary, result, _ = _run_resolve_sha_step(
            repository,
            api_response=api_response,
        )

        assert "Associated PR" not in summary
        assert "null" not in summary
        assert "### Resolved release target" in summary
        assert result.returncode == 0


def test_summary_links_lowest_numbered_merged_pr(tmp_path: Path) -> None:
    # When several merged PRs are associated with the commit (e.g. a merge to
    # main plus a later backport), the pick is deterministic: lowest number.
    pulls = [
        {"number": 5200, "merged_at": "2026-08-01T00:00:00Z"},
        {"number": 4857, "merged_at": "2026-07-20T18:53:15Z"},
    ]

    summary, _, _ = _run_resolve_sha_step(
        tmp_path,
        api_response=json.dumps(pulls),
    )

    assert (
        "| Associated PR | "
        "[#4857](https://github.com/langchain-ai/deepagents/pull/4857) |" in summary
    )
    assert "#5200" not in summary


def test_pr_parse_failure_does_not_block_release(tmp_path: Path) -> None:
    # gh exits 0 but returns non-JSON: the `if !` guard around jq must keep the
    # parse error from tripping `set -e` and aborting the release.
    summary, result, _ = _run_resolve_sha_step(
        tmp_path,
        api_response="not json {",
    )

    assert "Associated PR" not in summary
    assert "::warning::Could not parse the pull request" in result.stdout
    assert "### Resolved release target" in summary
    assert result.returncode == 0


def test_pr_lookup_failure_does_not_block_release(tmp_path: Path) -> None:
    summary, result, _ = _run_resolve_sha_step(
        tmp_path,
        api_response="GitHub API unavailable",
        api_exit=1,
    )

    assert "Associated PR" not in summary
    assert "::warning::Could not look up the pull request" in result.stdout
    assert "### Resolved release target" in summary
